---
title: "Members of the Neural Network reading group"
author: "Mauro Camara Escudero"
date: "3/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

The current members of the Neural Network Reading Group are listed below.
```{r, echo=FALSE}

members <- data.frame(
  Members = c(
"Alessio Zakaria", "Alexander Modell","Andi Wang","Andrea Becsek","Andrew Jones",
"Anthony Lee", "Chang Zhang","Christophe Andrieu", "Cindy Lim", "Conor Newton",
"Daniel Lawson", "Daniel Williams", "Hamza Alawiye", "Henry Reeve", "Ian Gallagher", 
"Jack Simons", "Jennifer Chakravarty","Mark Beaumont", "Mauro Camara Escudero", "Maximilian Werner", 
"Mingxuan Yi", "Nick Whiteley", "Patrick Rubin-Delanchy", "Pierre-Aurelien Gilliot", "Raphael Clifford",
"Robert Allison", "Sacha Lapins", "Sam Power", "Sam Stockman", "Sam Tickle", 
"Song Liu", "Tjun Yee Hoh", "Vladislav Tadic"),
  Status =     c("SPECTATOR", "SPECTATOR", "PRESENTER", "SPECTATOR", "SPECTATOR", 
                 "PRESENTER", "PRESENTER", "PRESENTER", "SPECTATOR", "SPECTATOR",
                 "SPECTATOR", "SPECTATOR", "SPECTATOR", "PRESENTER", "SPECTATOR", 
                 "SPECTATOR", "SPECTATOR", "PRESENTER", "PRESENTER", "SPECTATOR", 
                 "PRESENTER", "SPECTATOR", "PRESENTER", "PRESENTER", "SPECTATOR", 
                 "PRESENTER", "SPECTATOR", "PRESENTER", "SPECTATOR", "PRESENTER",
                 "PRESENTER", "SPECTATOR", "SPECTATOR")
)
knitr::kable(members) %>% 
  kable_styling(bootstrap_options = c("hover", "responsive")) %>% 
  row_spec(which(members$Status == "PRESENTER"), bold=F, color="white", background="#0066ff") %>% 
  row_spec(which(members$Status == "SPECTATOR"), bold=F, color="white", background="#A8A8A8")
```

