---
title: "Past Papers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here's a list of the papers/videos that have previously been presented.


<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>

<table>
  <tr>
    <th>Date</th>
    <th>Presented By</th>
    <th>Paper Title</th>
  </tr>
  <tr>
    <td>3rd December</td>
    <td>Pierre-Aurelien Gilliot</td>
    <td><a href="http://proceedings.mlr.press/v5/salakhutdinov09a/salakhutdinov09a.pdf" target="_blank">Deep Boltzmann Machines - Ruslan Salakhutdinov</a></td>
  </tr>
  <tr>
    <td>10th December</td>
    <td>Christophe Andrieu</td>
    <td><a href="https://www.youtube.com/watch?v=R5hSqeLSQC0&app=desktop" target="_blank">Multiscale Models for Image Classification and Physics with Deep Networks - Stéphane Mallat</a></td>
  </tr>
  <tr>
    <td>17th December</td>
    <td>Anthony Lee</td>
    <td><a href="https://arxiv.org/abs/1708.06633" target="_blank">Nonparametric regression using deep neural networks with ReLU activation function - Johannes Schmidt-Hieber</a></td>
  </tr>
  <tr>
    <td>10th March</td>
    <td>Patrick Rubin-Delanchy</td>
    <td><a href="https://arxiv.org/pdf/1902.04742.pdf" target="_blank">Uniform convergence may be unable to explain generalization in deep learning - Vaishnavh Nagarajan</a></td>
  </tr>
  <tr>
    <td>24th March</td>
    <td>Song Liu</td>
    <td><a href="https://arxiv.org/pdf/1806.07366.pdf" target="_blank">Neural Ordinary Differential Equations - Ricky T. Q. Chen</a></td>
  </tr>
    <tr>
    <td>7th April</td>
    <td>Mark Beaumont</td>
    <td><a href="https://arxiv.org/pdf/1901.10230.pdf" target="_blank">Partially Exchangeable Networks and Architectures for Learning Summary
Statistics in Approximate Bayesian Computation - Samuel Wiqvist</a></td>
  </tr>
    </tr>
  <tr>
    <td>14th April</td>
    <td>Mauro Camara Escudero</td>
    <td><a href="https://papers.nips.cc/paper/5269-expectation-backpropagation-parameter-free-training-of-multilayer-neural-networks-with-continuous-or-discrete-weights.pdf" target="_blank">Expectation Backpropagation: Parameter-Free
Training of Multilayer Neural Networks with
Continuous or Discrete Weights - Daniel Soudry</a></td>
  </tr>
  <tr>
    <td>21st April</td>
    <td>Mingxuan Yi</td>
    <td><a href="https://arxiv.org/pdf/1703.00810.pdf" target="_blank">Opening the black box of Deep Neural Networks
via Information - Ravid Schwartz-Ziv</a></td>
  </tr>
    <tr>
    <td>28th April</td>
    <td>Andi Wang</td>
    <td><a href="https://arxiv.org/pdf/1410.6460.pdf" target="_blank">Markov Chain Monte Carlo and Variational Inference:
Bridging the Gap - Tim Salimans</a></td>
  </tr>
    <tr>
    <td>5th May</td>
    <td>Sam Tickle</td>
    <td><a href="https://arxiv.org/pdf/1905.06913.pdf" target="_blank">Deep Learning for Multi-Scale Changepoint
Detection in Multivariate Time Series - Zahra Ebrahimzadeh</a></td>
  </tr>
  <tr>
    <td>26th May</td>
    <td>Pierre Aurelien Gilliot</td>
    <td><a href="https://arxiv.org/abs/1901.03416" target="_blank">Preventing Posterior Collapse with delta-VAEs - Ali Razavi</a></td>
  </tr>
    <tr>
    <td>2nd June</td>
    <td>Christophe Andrieu</td>
    <td><a href="https://arxiv.org/abs/2002.12253" target="_blank">MetFlow: A New Efficient Method for Bridging the Gap between Markov Chain Monte Carlo and Variational Inference - Achille Thin</a></td>
  </tr>
  <tr>
    <td>9nd June</td>
    <td>Anthony Lee</td>
    <td><a href="https://arxiv.org/pdf/1705.07642.pdf" target="_blank">From optimal transport to generative modeling:
the VEGAN cookbook - Olivier Bousquet</a></td>
  </tr>
</table>