---
title: "Reading Group Schedule"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(kableExtra)
```

The current schedule for the Neural Network reading group is


```{r, echo=FALSE}
# Members
members = c(
"Adam Yang", "Alessio Zakaria", "Alexander Modell","Andi Wang","Andrea Becsek",
"Andrew Jones", "Annie Gray", "Anthony Lee", "Ayalvadi Ganesh", "Benjamin Barrett", 
"Chang Zhang", "Christophe Andrieu", "Cindy Lim", "Conor Newton", "Dan Ward",
"Daniel Lawson", "Daniel Williams", "Ed Davis", "Hamza Alawiye", "Henry Reeve", 
"Ian Gallagher", "Jack Simons", "Jennifer Chakravarty","Mark Beaumont","Mauro Camara Escudero", 
"Maximilian Werner", "Mingxuan Yi", "Nick Whiteley","Patrick Rubin-Delanchy", "Pierre-Aurelien Gilliot", 
"Raphael Clifford", "Robert Allison", "Sacha Lapins", "Sam Power", "Sam Stockman", 
"Sam Tickle", "Shannon Williams", "Song Liu", "Tjun Yee Hoh", "Vladislav Tadic")
status = c("SPECTATOR", "SPECTATOR", "SPECTATOR", "PRESENTER", "SPECTATOR", 
           "SPECTATOR", "SPECTATOR", "PRESENTER", "SPECTATOR", "SPECTATOR", 
           "PRESENTER", "PRESENTER", "SPECTATOR", "SPECTATOR", "SPECTATOR",
           "PRESENTER", "SPECTATOR", "SPECTATOR", "SPECTATOR", "PRESENTER", 
           "SPECTATOR", "SPECTATOR", "SPECTATOR", "PRESENTER", "PRESENTER", 
           "SPECTATOR", "PRESENTER", "SPECTATOR", "PRESENTER", "PRESENTER", 
           "SPECTATOR", "PRESENTER", "SPECTATOR", "PRESENTER", "SPECTATOR", 
           "PRESENTER", "SPECTATOR", "PRESENTER", "SPECTATOR", "SPECTATOR")
presenting_members <- members[ifelse(status == "PRESENTER", T, F)]
# Date of Presentation
dates_tb1 <- seq(as.Date("2021-03-31"), as.Date("2021-05-12"), by="weeks")
dates_tb2 <- seq(as.Date("2021-05-19"), as.Date("2021-07-07"), by="weeks")
dates     <- c(dates_tb1, dates_tb2)
# Order of Presentations
index     <- c(7, 2, 3, 15, 8, 
               9, 1, 10, 12, 4, 
               14, 6, 13, 11, 5)
names <- presenting_members[index]
# ZOOM during COVID
location <- rep("ZOOM", length(names))
schedule <- data.frame(Date=dates,Name=names, Room=location)
# upcoming WEEK
monday = "2021-04-28"
knitr::kable(schedule) %>% 
    kable_styling(bootstrap_options = c("hover", "responsive")) %>% 
    row_spec(which(schedule$Date == monday), bold=F, color="white", background="#0066ff")
```



<!-- <style> -->
<!-- table, th, td { -->
<!--   border: 1px solid black; -->
<!--   border-collapse: collapse; -->
<!-- } -->
<!-- th, td { -->
<!--   padding: 15px; -->
<!-- } -->
<!-- </style> -->

<!-- <table> -->
<!--   <tr> -->
<!--     <th>Date</th> -->
<!--     <th>Name</th> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>17th December</td> -->
<!--     <td>Anthony Lee</td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>14th January</td> -->
<!--     <td>Song Liu</td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>21st January</td> -->
<!--     <td>Mark Beaumont</td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>28th January</td> -->
<!--     <td>Mauro Camara Escudero</td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>4th February</td> -->
<!--     <td>Patrick Rubin-Delanchy</td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>11th February</td> -->
<!--     <td>Andi Wang</td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>18th February</td> -->
<!--     <td>Mathieu Gerber</td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>25th February</td> -->
<!--     <td>Nick Whiteley</td> -->
<!--   </tr> -->
<!-- </table> -->


