---
title: 'Neural Tangent Kernel: Convergence and Generalization in Neural Networks'
author: Mauro Camara Escudero
date: '2020-11-23'
slug: neural-tangent-kernel-convergence-and-generalization-in-neural-networks
categories:
  - kernel methods
  - neural-networks
tags:
  - kernel methods
  - neural-networks
---
On Monday $23^{\text{rd}}$ of November Mingxuan presented [Neural Tangent Kernel:
Convergence and Generalization in Neural Networks](https://arxiv.org/pdf/1806.07572.pdf). You can find the abstract below:

> At initialization, artificial neural networks (ANNs) are equivalent to Gaussian
processes in the infinite-width limit (16; 4; 7; 13; 6), thus connecting them to
kernel methods. We prove that the evolution of an ANN during training can also
be described by a kernel: during gradient descent on the parameters of an ANN,
the network function fθ (which maps input vectors to output vectors) follows the
kernel gradient of the functional cost (which is convex, in contrast to the parameter
cost) w.r.t. a new kernel: the Neural Tangent Kernel (NTK). This kernel is central
to describe the generalization features of ANNs. While the NTK is random at
initialization and varies during training, in the infinite-width limit it converges
to an explicit limiting kernel and it stays constant during training. This makes it
possible to study the training of ANNs in function space instead of parameter space.
Convergence of the training can then be related to the positive-definiteness of the
limiting NTK. We prove the positive-definiteness of the limiting NTK when the
data is supported on the sphere and the non-linearity is non-polynomial.
We then focus on the setting of least-squares regression and show that in the infinitewidth limit, the network function fθ follows a linear differential equation during
training. The convergence is fastest along the largest kernel principal components
of the input data with respect to the NTK, hence suggesting a theoretical motivation
for early stopping.
Finally we study the NTK numerically, observe its behavior for wide networks,
and compare it to the infinite-width limit.
