---
title: Uniform convergence may be unable to explain generalization in deep learning
author: Mauro Camara Escudero
date: '2020-03-10'
slug: uniform-convergence-may-be-unable-to-explain-generalization-in-deep-learning
categories:
  - deep-learning
  - generalization-error
  - neural-networks
tags:
  - neural-networks
  - deep-learning
  - deep-neaural-networks
  - generalization-error
---
On Tuesday 10$^{\text{th}}$ of March Patrick Rubin-Delanchy presented the 2019 NeurIPS [paper](https://arxiv.org/pdf/1902.04742.pdf) winner of the Outstanding New Directions Paper Award, titled "Uniform convergence may be unable to explain generalization in deep learning" by Vaishnavh Nagarajan and J. Zico Kolter.

The abstract is given below.

> Aimed at explaining the surprisingly good generalization behavior of overparameterized deep networks, recent works have developed a variety of generalization
bounds for deep learning, all based on the fundamental learning-theoretic technique
of uniform convergence. While it is well-known that many of these existing bounds
are numerically large, through numerous experiments, we bring to light a more
concerning aspect of these bounds: in practice, these bounds can increase with
the training dataset size. Guided by our observations, we then present examples
of overparameterized linear classifiers and neural networks trained by gradient
descent (GD) where uniform convergence provably cannot “explain generalization”
– even if we take into account the implicit bias of GD to the fullest extent possible.
More precisely, even if we consider only the set of classifiers output by GD, which
have test errors less than some small $\epsilon$ in our settings, we show that applying
(two-sided) uniform convergence on this set of classifiers will yield only a vacuous
generalization guarantee larger than 1 − $\epsilon$. Through these findings, we cast doubt
on the power of uniform convergence-based generalization bounds to provide a
complete picture of why overparameterized deep networks generalize well