---
title: 'Toward a theory of optimization for over-parameterized systems of non-linear
  equations: the lessons of deep learning'
author: Mauro Camara Escudero
date: '2020-12-07'
slug: toward-a-theory-of-optimization-for-over-parameterized-systems-of-non-linear-equations-the-lessons-of-deep-learning
categories:
  - deep-learning
tags:
  - deep-learning
---
On Monday $7^{\text{th}}$ of December Andi presented [Toward a theory of optimization for over-parameterized systems of non-linear equations: the lessons of deep learning](http://arxiv.org/abs/2003.00307). The abstract is given below:

> The success of deep learning is due, to a great extent, to the remarkable effectiveness of gradient-based optimization methods applied to large neural networks. In this work we isolate some general mathematical structures allowing for efficient optimization in over-parameterized systems of non-linear equations, a setting that includes deep neural networks. In particular, we show that optimization problems corresponding to such systems are not convex, even locally, but instead satisfy the Polyak-Lojasiewicz (PL) condition allowing for efficient optimization by gradient descent or SGD. We connect the PL condition of these systems to the condition number associated to the tangent kernel and develop a non-linear theory parallel to classical analyses of over-parameterized linear equations. We discuss how these ideas apply to training shallow and deep neural networks. Finally, we point out that tangent kernels associated to certain large system may be far from constant, even locally. Yet, our analysis still allows to demonstrate existence of solutions and convergence of gradient descent and SGD.
