---
title: 'Markov Chain Monte Carlo and Variational Inference: Bridging the Gap'
author: Mauro Camara Escudero
date: '2020-04-28'
slug: markov-chain-monte-carlo-and-variational-inference-bridging-the-gap
categories:
  - mcmc
  - variational-inference
  - markov-chain-monte-carlo
  - hamiltonian-monte-carlo
  - hmc
  - neural-networks
  - deep-learning
tags:
  - variational-inference
  - mcmc
  - hmc
---

On Tuesday $28^{\text{th}}$ of April Andi Wang presented [Markov Chain Monte Carlo and Variational Inference:
Bridging the Gap - Tim Salimans](https://arxiv.org/pdf/1410.6460.pdf). His slides are available [here](https://neuralnetworksbristol.netlify.com/AndiWang.pdf) and the abstract is given below.

> Recent advances in stochastic gradient variational inference have made it possible to
perform variational Bayesian inference with
posterior approximations containing auxiliary random variables. This enables us to
explore a new synthesis of variational inference and Monte Carlo methods where we incorporate one or more steps of MCMC into
our variational approximation. By doing so
we obtain a rich class of inference algorithms
bridging the gap between variational methods and MCMC, and offering the best of
both worlds: fast posterior approximation
through the maximization of an explicit objective, with the option of trading off additional computation for additional accuracy.
We describe the theoretical foundations that
make this possible and show some promising
first results.