---
title: 'From optimal transport to generative modeling: the VEGAN cookbook'
author: Mauro Camara Escudero
date: '2020-06-09'
slug: from-optimal-transport-to-generative-modeling-the-vegan-cookbook
categories:
  - optimal transport
  - vae
  - aae
  - gan
  - deep-learning
tags:
  - optimal transport
  - vae
  - aae
  - gan
  - deep-learning
---

On Tuesday 9th of June Anthony Lee presented [From optimal transport to generative modeling:
the VEGAN cookbook](https://arxiv.org/pdf/1705.07642.pdf). The abstract is given below:

> We study unsupervised generative modeling in terms of the optimal transport (OT) problem
between true (but unknown) data distribution PX and the latent variable model distribution
PG. We show that the OT problem can be equivalently written in terms of probabilistic
encoders, which are constrained to match the posterior and prior distributions over the latent
space. When relaxed, this constrained optimization problem leads to a penalized optimal
transport (POT) objective, which can be efficiently minimized using stochastic gradient descent
by sampling from PX and PG. We show that POT for the 2-Wasserstein distance coincides with
the objective heuristically employed in adversarial auto-encoders (AAE) [1], which provides the
first theoretical justification for AAEs known to the authors. We also compare POT to other
popular techniques like variational auto-encoders (VAE) [2]. Our theoretical results include
(a) a better understanding of the commonly observed blurriness of images generated by VAEs,
and (b) establishing duality between Wasserstein GAN [3] and POT for the 1-Wasserstein
distance.
