---
title: Learning Latent Subspaces in Variational Autoencoders
author: Mauro Camara Escudero
date: '2020-11-09'
slug: learning-latent-subspaces-in-variational-autoencoders
categories:
  - vae
  - variational-inference
  - variational-autoencoder
  - generative-models
  - mnist
  - deep-learning
tags:
  - vae
  - variational-inference
  - variational autoencoder
  - deep-learning
  - generative-models
  - mnist
---

On Monday $9^{\text{th}}$ of November Pierre presented [Learning Latent Subspaces in
Variational Autoencoders](https://arxiv.org/pdf/1812.06190.pdf) by Klys et al. The slides are available [here](https://neuralnetworksbristol.netlify.com/Conditional_VAE_Pierre.pdf) and the abstract is given below:

> Variational autoencoders (VAEs) [10, 20] are widely used deep generative models
capable of learning unsupervised latent representations of data. Such representations are often difficult to interpret or control. We consider the problem of
unsupervised learning of features correlated to specific labels in a dataset. We
propose a VAE-based generative model which we show is capable of extracting
features correlated to binary labels in the data and structuring it in a latent subspace
which is easy to interpret. Our model, the Conditional Subspace VAE (CSVAE),
uses mutual information minimization to learn a low-dimensional latent subspace
associated with each label that can easily be inspected and independently manipulated. We demonstrate the utility of the learned representations for attribute
manipulation tasks on both the Toronto Face [23] and CelebA [15] datasets.
