---
title: The Thermodynamic Variational Objective
author: Mauro Camara Escudero
date: '2021-04-14'
slug: the-thermodynamic-variational-objective
categories:
  - variational
  - variational-inference
tags:
  - variational-inference
  - varitional
  - neural-networks
---

On Wednesday the $14^{\text{th}}$ of April Chang presented [The Thermodynamic Variational Objective](https://arxiv.org/pdf/1907.00031.pdf). The abstract is given below.

> We introduce the thermodynamic variational objective (TVO) for learning in both
continuous and discrete deep generative models. The TVO arises from a key
connection between variational inference and thermodynamic integration that
results in a tighter lower bound to the log marginal likelihood than the standard
variational evidence lower bound (ELBO) while remaining as broadly applicable.
We provide a computationally efficient gradient estimator for the TVO that applies
to continuous, discrete, and non-reparameterizable distributions and show that the
objective functions used in variational inference, variational autoencoders, wake
sleep, and inference compilation are all special cases of the TVO. We use the
TVO to learn both discrete and continuous deep generative models and empirically
demonstrate state of the art model and inference network learning.
