---
title: A Likelihood-Free Inference Framework for Population Genetic Data using Exchangeable
  Neural Networks
author: ''
date: '2021-07-02'
slug: a-likelihood-free-inference-framework-for-population-genetic-data-using-exchangeable-neural-networks
categories:
  - likelihood-free
  - exchangeable-networks
tags:
  - likelihood-free
---
On Wednesday the $30^{\text{th}}$ of June, Dan presented [A Likelihood-Free Inference Framework for Population Genetic Data using Exchangeable Neural Networks](https://proceedings.neurips.cc/paper/2018/hash/2e9f978b222a956ba6bdf427efbd9ab3-Abstract.html). The abstract is below.

> An explosion of high-throughput DNA sequencing in the past decade has led to a surge of interest in population-scale inference with whole-genome data. Recent work in population genetics has centered on designing inference methods for relatively simple model classes, and few scalable general-purpose inference techniques exist for more realistic, complex models. To achieve this, two inferential challenges need to be addressed: (1) population data are exchangeable, calling for methods that efficiently exploit the symmetries of the data, and (2) computing likelihoods is intractable as it requires integrating over a set of correlated, extremely high-dimensional latent variables. These challenges are traditionally tackled by likelihood-free methods that use scientific simulators to generate datasets and reduce them to hand-designed, permutation-invariant summary statistics, often leading to inaccurate inference. In this work, we develop an exchangeable neural network that performs summary statistic-free, likelihood-free inference. Our framework can be applied in a black-box fashion across a variety of simulation-based tasks, both within and outside biology. We demonstrate the power of our approach on the recombination hotspot testing problem, outperforming the state-of-the-art.