---
title: Neural Word Embedding as Implicit Matrix Factorization
author: Mauro Camara Escudero
date: '2021-02-10'
slug: neural-word-embedding-as-implicit-matrix-factorization
categories:
  - word embedding
  - matrix factorization
  - neural-networks
tags:
  - nlp
  - word embedding
  - matrix factorization
  - neural-networks
  - deep-learning
  - deep-neural-network
---
On Wednesday the $10^{\text{th}}$ of February Patrick presented [Neural Word Embedding
as Implicit Matrix Factorization](https://papers.nips.cc/paper/2014/file/feab05aa91085b7a8012516bc3533958-Paper.pdf) by Levy and Goldberg. You can find some hand-written notes [here](/NWE_Patrick.pdf). The abstract is given below.

> We analyze skip-gram with negative-sampling (SGNS), a word embedding
method introduced by Mikolov et al., and show that it is implicitly factorizing
a word-context matrix, whose cells are the pointwise mutual information (PMI) of
the respective word and context pairs, shifted by a global constant. We find that
another embedding method, NCE, is implicitly factorizing a similar matrix, where
each cell is the (shifted) log conditional probability of a word given its context.
We show that using a sparse Shifted Positive PMI word-context matrix to represent
words improves results on two word similarity tasks and one of two analogy tasks.
When dense low-dimensional vectors are preferred, exact factorization with SVD
can achieve solutions that are at least as good as SGNS’s solutions for word similarity tasks. On analogy questions SGNS remains superior to SVD. We conjecture
that this stems from the weighted nature of SGNS’s factorization.