---
title: Sequential Neural Posterior and Likelihood Approximation
author: Mauro Camara Escudero
date: '2021-03-31'
slug: sequential-neural-posterior-and-likelihood-approximation
categories:
  - likelihood-free
  - normalizing-flows
  - generative-models
tags:
  - generative-models
  - normalizing-flows
  - likelihood-free
---
On Wednesday the $31^{\text{th}}$ of March, Mark presented [Sequential Neural Posterior and Likelihood Approximation](https://arxiv.org/abs/2102.06522). The abstract is given below:

> We introduce the sequential neural posterior and likelihood approximation (SNPLA) algorithm. SNPLA is a normalizing flows-based algorithm for inference in implicit models. Thus, SNPLA is a simulation-based inference method that only requires simulations from a generative model. Compared to similar methods, the main advantage of SNPLA is that our method jointly learns both the posterior and the likelihood. SNPLA completely avoid Markov chain Monte Carlo sampling and correction-steps of the parameter proposal function that are introduced in similar methods, but that can be numerically unstable or restrictive. Over four experiments, we show that SNPLA performs competitively when utilizing the same number of model simulations as used in other methods, even though the inference problem for SNPLA is more complex due to the joint learning of posterior and likelihood function.