---
title: 'NeuralFDR: Learning Discovery Thresholds from Hypothesis Features'
author: Mauro Camara Escudero
date: '2021-03-03'
slug: neuralfdr-learning-discovery-thresholds-from-hypothesis-features
categories:
  - neural networks
tags:
  - neural-networks
---
On Wednesday the $3^{\text{th}}$ of March Henry presented [NeuralFDR: Learning Discovery Thresholds from Hypothesis Features](https://arxiv.org/abs/1711.01312) by Xia et al. The abstract is given below.

> As datasets grow richer, an important challenge is to leverage the full features in the data to maximize the number of useful discoveries while controlling for false positives. We address this problem in the context of multiple hypotheses testing, where for each hypothesis, we observe a p-value along with a set of features specific to that hypothesis. For example, in genetic association studies, each hypothesis tests the correlation between a variant and the trait. We have a rich set of features for each variant (e.g. its location, conservation, epigenetics etc.) which could inform how likely the variant is to have a true association. However popular testing approaches, such as Benjamini-Hochberg's procedure (BH) and independent hypothesis weighting (IHW), either ignore these features or assume that the features are categorical or uni-variate. We propose a new algorithm, NeuralFDR, which automatically learns a discovery threshold as a function of all the hypothesis features. We parametrize the discovery threshold as a neural network, which enables flexible handling of multi-dimensional discrete and continuous features as well as efficient end-to-end optimization. We prove that NeuralFDR has strong false discovery rate (FDR) guarantees, and show that it makes substantially more discoveries in synthetic and real datasets. Moreover, we demonstrate that the learned discovery threshold is directly interpretable.