---
title: Deep Gaussian Processes
author: Mauro Camara Escudero
date: '2021-06-26'
slug: deep-gaussian-processes
categories:
  - deep-learning
  - gaussian-processes
tags:
  - deep-learning
  - gaussian-processes
---
On Wednesday the $23^{rd}$ of June Sam presented [Deep Gaussian Processes](http://proceedings.mlr.press/v31/damianou13a.html). The abstract is given below.

> In this paper we introduce deep Gaussian process (GP) models. Deep GPs are a deep belief network based on Gaussian process mappings. The data is modeled as the output of a multivariate GP. The inputs to that Gaussian process are then governed by another GP. A single layer model is equivalent to a standard GP or the GP latent variable model (GP-LVM). We perform inference in the model by approximate variational marginalization. This results in a strict lower bound on the marginal likelihood of the model which we use for model selection (number of layers and nodes per layer). Deep belief networks are typically applied to relatively large data sets using stochastic gradient descent for optimization. Our fully Bayesian treatment allows for the application of deep models even when data is scarce. Model selection by our variational bound shows that a five layer hierarchy is justified even when modelling a digit data set containing only 150 examples.